font_family      Monocraft Nerd Font
font_size        13
bold_font        auto
italic_font      auto
bold_italic_font auto
mouse_hide_wait  2.0
cursor_shape     block
# url_color        #0087bd
url_style        dotted
adjust_line_height 120%
confirm_os_window_close 0
background_opacity 1

map ctrl+c copy_or_interrupt
map ctrl+p paste_from_clipboard

# BEGIN_KITTY_THEME
# Snow Light
include current-theme.conf
# END_KITTY_THEME
